// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication.Db;

namespace WebApplication.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210406080328_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApplication.Models.Quote", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Author")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Quotes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Nelson Mandela",
                            InsertDate = new DateTime(2021, 4, 6, 13, 3, 28, 568, DateTimeKind.Local).AddTicks(5165),
                            Text = "The greatest glory in living lies not in never falling, but in rising every time we fall."
                        },
                        new
                        {
                            Id = 2,
                            Author = "Walt Disney",
                            InsertDate = new DateTime(2021, 4, 6, 13, 3, 28, 569, DateTimeKind.Local).AddTicks(6992),
                            Text = "The way to get started is to quit talking and begin doing."
                        },
                        new
                        {
                            Id = 3,
                            Author = "Eleanor Roosevelt",
                            InsertDate = new DateTime(2021, 4, 6, 13, 3, 28, 569, DateTimeKind.Local).AddTicks(7013),
                            Text = "If life were predictable it would cease to be life, and be without flavor."
                        },
                        new
                        {
                            Id = 4,
                            Author = "John Lennon",
                            InsertDate = new DateTime(2021, 4, 6, 13, 3, 28, 569, DateTimeKind.Local).AddTicks(7015),
                            Text = "Life is what happens when you're busy making other plans."
                        },
                        new
                        {
                            Id = 5,
                            Author = "Franklin D. Roosevelt",
                            InsertDate = new DateTime(2021, 4, 6, 13, 3, 28, 569, DateTimeKind.Local).AddTicks(7016),
                            Text = "When you reach the end of your rope, tie a knot in it and hang on."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
